services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --workers 2
    volumes: [".:/code"]
    depends_on: [neo4j, redis]
    environment:
      - PYTHONPATH=/code
    ports:
      - "8000:8000"
  neo4j:
    image: neo4j:5.16
    environment:
      NEO4J_AUTH: none
    ports: ["7474:7474","7687:7687"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
