## docker-compose.yml

version: "3.9"
services:
  api:
    build: ./docker
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --workers 2
    volumes: [".:/code"]
    depends_on: [neo4j, redis]
    environment:
      - PYTHONPATH=/code
  neo4j:
    image: neo4j:5.16
    environment:
      NEO4J_AUTH: none
    ports: ["7474:7474","7687:7687"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
